- name: Check k8s host
  hosts: localhost
  connection: local
  tasks:
    - name: Wait for k8s port 22
      wait_for:
        host: "192.168.199.216"
        port: 22
      
- name: Deploy bot
  hosts: localhost
  tasks:
    - name: Apply bot deployment
      kubernetes.core.k8s:
        apply: true
        namespace: "buldakova-ma"
        template: ./movie-bot-deployment.yaml
