- name: run local terraform
  hosts: localhost
  connection: local
  tasks:
    - name: Run terraform
      terraform:
        project_path: "../terraform"
        force_init: yes
        state: present
      register: trfrm

    - name: Add movie_bot
      add_host:
        name: movie_bot
        groups: nodes
        ansible_host: "{{ trfrm.outputs.servers.value.movie_bot }}"
        ansible_ssh_private_key_file: ~/.ssh/key
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        
- name: Timeout for instance creating
  hosts: localhost
  connection: local     
  tasks:
    - name: Wait for server port 22
      wait_for:
        host: "{{ trfrm.outputs.servers.value.movie_bot }}"
        port: 22

- name: Set up bot
  hosts: movie_bot
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install JDK 17
      apt:
        update_cache: yes
        name: openjdk-17-jdk-headless
        state: present

    - name: Copy jar archive
      copy:
        src: "{{ jar_path }}"
        dest: /home/ubuntu/target

    - name: Set application as service
      copy:
        src: "{{ server_service }}"
        dest: /etc/systemd/system/

    - name: Deploy Java application
      systemd:
        daemon_reload: true
        state: restarted
        name: bot